# Copyright (c) 2021, The Linux Foundation. All rights reserved.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; version 2.1.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

[Global]
default-profile = default
use-dolby-hw-loopback = no

[Port headset]
description = headset
direction = out
priority = 500
presence = dynamic
device = AUDIO_DEVICE_OUT_WIRED_HEADSET

[Port headphone]
description = headphone
direction = out
priority = 300
presence = dynamic
device = AUDIO_DEVICE_OUT_WIRED_HEADPHONE

[Port headset-mic]
description = headset-mic
direction = in
priority = 500
presence = dynamic
device = AUDIO_DEVICE_IN_WIRED_HEADSET

[Profile default]
description = Default qahw profile
priority = 500
max-sink-channels = 8
max-source-channels = 2
port-names = headset headset-mic headphone

[Sink offload0]
description = qahw sink to play pcm/compressed music data via offload path
type = offload
flags = AUDIO_OUTPUT_FLAG_COMPRESS_OFFLOAD AUDIO_OUTPUT_FLAG_NON_BLOCKING AUDIO_OUTPUT_FLAG_DIRECT
default-encoding = pcm
default-sample-rate = 48000
default-sample-format = s16le
default-channel-map = front-left,front-right
encodings = pcm mpeg aac
port-names = headset headphone
presence = always
use-hw-volume = true

[Sink primary]
description = qahw sink to play pcm non-music data via primary path
type = primary
flags = AUDIO_OUTPUT_FLAG_PRIMARY
default-encoding = pcm
default-sample-rate = 48000
default-sample-format = s16le
default-channel-map = front-left,front-right
encodings = pcm
port-names = headset headphone
presence = always
use-hw-volume = false

[Source regular0]
description = qahw source to capture pcm via regular record path
type = regular
flags = AUDIO_INPUT_FLAG_NONE
default-encoding = pcm
default-sample-rate = 48000
default-sample-format = s16le
default-channel-map = front-left,front-right
encodings = pcm
port-names = headset-mic
presence = always
source-type = AUDIO_SOURCE_MIC

[Source regular0_fluence]
description = qahw source to capture pcm via regular record path with fluence enabled
type = regular
flags = AUDIO_INPUT_FLAG_NONE
default-encoding = pcm
default-sample-rate = 16000
default-sample-format = s16le
default-channel-map = mono
encodings = pcm
sample-rates = 8000 16000 32000 48000 ;Fluence supports only these rates
sample-formats = s16le ;Fluence is supported only for 16bit
channel-maps = mono ;Fluence is supported for mono channel only
use-qahw-processing = fluence
port-names = headset-mic
presence = always
source-type = AUDIO_SOURCE_MIC
